---
  - name: Add nginx repo
    ansible.builtin.template:
      src: nginx.repo.j2
      dest: /etc/yum.repos.d/nginx.repo
      owner: root
      group: root
      mode: 0644


  - name: Install nginx
    ansible.builtin.yum:
      name: nginx
      state: present
      update_cache: yes
    notify: start nginx
