---
dependency:
  name: galaxy
  enable: false
  
driver:
  name: docker

platforms:
  - name: ubuntu-bionic
    image: ubuntu:bionic
    pre_build_image: true
  - name: ubuntu-focal
    image: ubuntu:focal
    pre_build_image: true
  - name: debian-buster
    image: debian:buster
    pre_build_image: true
  - name: debian-bullseye
    image: debian:bullseye
    pre_build_image: true
#  - name: example-tag
#    image: example:tag
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    priveleged: true
#    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .